version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  mongo_db:
    image: mongo:5.0.6
    restart: always
    ports:
      - 27017:27017
  api_gateway:
    image: nginx:latest
    volumes:
      - ./sm-evaluation-ms-api-gateway/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "8000:80"